[general]
live_config_reload = true

[font]
size = 15
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Menlo", style = "Italic" }
offset = { x = -1, y = 0 }

# For font smoothening on macOS
# defaults write org.alacritty AppleFontSmoothing -int 0

[window]
startup_mode = "Maximized"
dynamic_title = true
option_as_alt = "OnlyLeft"
opacity = 1.0
decorations_theme_variant = "Dark"

[env]
TERM = "xterm-256color"

[scrolling]
history = 100000

[terminal]
osc52 = "CopyPaste"
shell = { program = "/opt/homebrew/bin/fish", args = ["-l"] }

[selection]
save_to_clipboard = true

# ----------------------------
# Colors (Tomorrow Night Gogh)

# Default colors
[colors.primary]
background = '#1d1f21'
foreground = '#c5c8c6'

[colors.cursor]
text = '#1d1f21'
cursor = '#C5C8C6'

# Normal colors
[colors.normal]
black   = '#282A2E'
red     = '#CC6666'
green   = '#b5bd68'
yellow  = '#F0C674'
blue    = '#81a2be'
magenta = '#b294bb'
cyan    = '#8ABEB7'
white   = '#C5C8C6'

# Bright colors
[colors.bright]
black   = '#969896'
red     = '#CC6666'
green   = '#B5BD68'
yellow  = '#f0c674'
blue    = '#81a2be'
magenta = '#B294BB'
cyan    = '#8ABEB7'
white   = '#FFFFFF'
